<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="StandaloneDreadTracker.UI.Avalonia" />
		<InternalsVisibleTo Include="StandaloneDreadTracker.UI.Avalonia.Android" />
		<InternalsVisibleTo Include="StandaloneDreadTracker.UI.Avalonia.Desktop" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="ReactiveUI" />
		<PackageReference Include="ReactiveUI.SourceGenerators">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Arcanox.AppCore\Arcanox.AppCore\Arcanox.AppCore.csproj" />
		<ProjectReference Include="..\DreadRemoteConnector\DreadRemoteConnector.csproj" />
	</ItemGroup>

</Project>