<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Lua\**\*.lua" />
	</ItemGroup>

</Project>