<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>StandaloneDreadTracker</AssemblyName>
		<OutputType>WinExe</OutputType>
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<!-- Trimming-related properties -->
	<PropertyGroup>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>partial</TrimMode>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
	</PropertyGroup>

	<ItemGroup>
		<TrimmerRootAssembly Include="ReactiveUI" />
		<TrimmerRootAssembly Include="StandaloneDreadTracker.App" />
		<TrimmerRootAssembly Include="StandaloneDreadTracker" />
	</ItemGroup>

	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StandaloneDreadTracker.UI.Avalonia\StandaloneDreadTracker.UI.Avalonia.csproj" />
	</ItemGroup>
</Project>